Modify localstream error handling
100mslive/100ms-web-v1 pull request #21
Opened 2021-01-06 07:52 UTC by eswarclynn

- Check whether mediaDevices exists.
- Modify error messages.
- Continue call for TypeError.

2021-01-06 08:36 UTC, apnerve requested changes

2021-01-06 08:36 UTC, apnerve commented on src/utils/index.js
>    } else if (error.name == 'OverconstrainedError') {
Refactor the if/else statements to use a map instead. So we have a map of errors to the title/messages. Adding more if/else later on becomes unmanageable and also increases cyclomatic complexity

2021-01-06 09:49 UTC, eswarclynn commented on src/utils/index.js
>    } else if (error.name == 'OverconstrainedError') {
Refactored to use a map.

2021-02-02 04:41 UTC, apnerve approved these changes
👍

2021-02-02 11:03 UTC, merged